### ISSUE TITLE
$35 | Navigation not working on some links

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/navigation-component#69] opened 2019-12-20 07:49 UTC
1. When on https://www.topcoder.com/challenges click "More" -> click "Explore" -> try click on "TCO" link is not working.
2. Blog link under "More" -> click "Explore" is not working. Shows 404 error instead of the blog

Note: When you resize the browser window, and access the menu items by clicking "More", one of the level 1 menus are already selected (even though the user has not yet navigated to it) and the user is not able to access that particular page.
<img width="774" alt="Screenshot 2019-12-20 at 1 49 08 PM" src="https://user-images.githubusercontent.com/58783823/71240683-ca23cb80-232f-11ea-8f2a-f1182fdb1a70.png">
![Uploading Screenshot 2019-12-20 at 1.50.02 PM.png…]()

**Comment by kkartunov** [comment] 2019-12-20 08:05
3. Actually click "More" -> click "Tracks " -> try click on "Competitive Programming" is also not working

**Comment by SathyaJayabal** [comment] 2019-12-20 08:06
@kkartunov , I cant seem to reproduce issue #1. 
Which link do you mean by "More" in the challenges page?

**Comment by kkartunov** [comment] 2019-12-20 08:07
@SathyaJayabal In the navi

**Comment by SathyaJayabal** [comment] 2019-12-20 08:13
@kkartunov Thank you, got it.

**Comment by nithyaasworld** [comment] 2019-12-20 08:37
@kkartunov Can you share the Device and Browser you are checking with?

**Comment by SathyaJayabal** [comment] 2019-12-20 08:43
another example
<img width="776" alt="Screenshot 2019-12-20 at 1 50 02 PM" src="https://user-images.githubusercontent.com/58783823/71241775-71096700-2332-11ea-90a0-46aee44e11f9.png">

**Comment by luizrrodrigues** [comment] 2020-01-07 20:36
Note: This issue only happen when open menu via "More"

**Comment by rashmi73** [comment] 2020-01-09 15:55
@luizrrodrigues not reproducible because no such "TCO" menu present

**Comment by luizrrodrigues** [comment] 2020-01-09 16:01
@rashmi73 Try check this in Firefox or reduce the window size to show "MORE" menu item.

**Comment by SathyaJayabal** [comment] 2020-01-09 16:02
@rashmi73 look under more->explore

**Comment by yoution** [comment] 2020-01-15 04:30
@luizrrodrigues  please assign to me

**Comment by yoution** [comment] 2020-01-15 05:26
@luizrrodrigues  https://github.com/topcoder-platform/navigation-component/pull/117
please review

**Comment by luizrrodrigues** [comment] 2020-01-15 19:46
@yoution Links working, but currently when access **Compete** submenu, will show the position to last one.

Check:
[Screen Recording 2020-01-15 at 16.35.23.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4067170/Screen.Recording.2020-01-15.at.16.35.23.mov.zip)

**Comment by SathyaJayabal** [comment] 2020-01-21 10:39
Verified in test env. Please see attached video
[more_first link.mov.zip](https://github.com/topcoder-platform/navigation-component/files/4090603/more_first.link.mov.zip)

**Comment by macs054** [comment] 2020-02-27 04:54
Verified in Beta
[issue_69_beta.zip](https://github.com/topcoder-platform/navigation-component/files/4259509/issue_69_beta.zip)

**Comment by SathyaJayabal** [comment] 2020-02-28 03:18
verified on prod
<img width="801" alt="Screenshot 2020-02-28 at 8 47 38 AM" src="https://user-images.githubusercontent.com/58783823/75507434-0c8c1780-5a07-11ea-8464-fea0e579d5eb.png">

**Closed by SathyaJayabal** 2020-02-28 03:18 UTC
Labels: P2, Prod Env, QA Pass, nav_Assigned, nav_FixAccepted, nav_Paid
