### ISSUE TITLE
Component should not apply body styles

### ISSUE THREAD

**Issue by kkartunov** [topcoder-platform/navigation-component#68] opened 2019-12-20 07:34 UTC
Navi component should not apply body styles as they break multiple pages.
The component should be contained and not using such hacks: https://github.com/topcoder-platform/navigation-component/blob/5e91a32da09288cf18f79e18f10d7efe4a364ffd/src/assets/sass/style.scss#L10 leaking global styles.

The result is a gray background on:
- all Track pages
- Explore - TCO, Explore - Programs
- Thrive - all pages

**Comment by lakshmiathreya** [comment] 2019-12-20 08:00
cc @nithyaasworld @SathyaJayabal

**Comment by SathyaJayabal** [comment] 2019-12-20 08:31
Closing this as its a duplicate of
https://github.com/topcoder-platform/community-app/issues/3532

**Comment by kkartunov** [comment] 2019-12-23 18:16
cc @luizrrodrigues @nithyaasworld @SathyaJayabal when will this be fixed?

**Comment by luizrrodrigues** [comment] 2019-12-23 18:28
@kkartunov We'll run a Bug Bash to all navigation issues.

But not able to new deploy until @sushilshinde back (next week)

**Comment by SathyaJayabal** [comment] 2020-01-03 12:05
Verified in production
<img width="1427" alt="Screenshot 2020-01-03 at 5 32 58 PM" src="https://user-images.githubusercontent.com/58783823/71722596-65985e80-2e4f-11ea-961c-313418ad8969.png">

**Closed by SathyaJayabal** 2020-01-03 12:05 UTC
Labels: P2, Prod Env
